config/routes.rb
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

Rails.application.routes.draw do
  resources :data_bundles, except: [:new]

  root 'data_bundles#index'
  devise_for :users, controllers: {omniauth_callbacks: 'callbacks'}
end

app/models/data_bundle.rb
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

class DataBundle < ActiveRecord::Base
  paginates_per 10
  mount_uploader :file, ::DataBundleUploader

  belongs_to :user

  validates :name, :user_id, :file, presence: true

  after_create :extract_file

  EXTRACTED_DIRECTORY = 'extracted_source'
  EXTRACTED_WORKFLOW_PATH = 'workflow_source'

  def file_path
    "#{file.root}/#{file.store_dir}/#{EXTRACTED_DIRECTORY}/"
  end

  def extract_file
    Archive::Zip.extract(file.path, "#{file_path}")
    Archive::Zip.extract("#{file_path}workflow.wfbundle", "#{file_path}#{DataBundle::EXTRACTED_WORKFLOW_PATH}")
  end
end

app/controllers/data_bundles_controller.rb
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

class DataBundlesController < ApplicationController
  before_action :set_data_bundle, only: [:show, :edit, :update, :destroy]

  # GET /data_bundles
  def index
    if user_signed_in?
      @data_bundles = current_user.databundles.page(params[:page])
      @data_bundle = DataBundle.new
    end
  end

  # GET /data_bundles/1
  # GET /data_bundles/1.json
  def show
    @data_bundle = @data_bundle.decorate
    respond_to do |format|
      format.html
      # format.json { render json: @data_bundle.to_json }
      format.json { render :json => {:workflow => @data_bundle.to_dataHashObject,
                                     :provenance =>  @data_bundle.provenanceMain } }
    end
  end

  # GET /data_bundles/1/edit
  def edit
    redirect_to data_bundles_path,  notice: "Success"
  end

  # POST /data_bundles
  def create
    @data_bundle = current_user.databundles.new(data_bundle_params)

    if @data_bundle.save
      redirect_to @data_bundle, notice: 'Data bundle was successfully created.'
    else
      render :edit
    end
  end

  # PATCH/PUT /data_bundles/1
  def update
    if @data_bundle.update(data_bundle_params)
      redirect_to @data_bundle, notice: 'Data bundle was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /data_bundles/1
  def destroy
    @data_bundle.destroy
    redirect_to data_bundles_url, notice: 'Data bundle was successfully destroyed.'
  end

  def redirectToLogin
    redirect_to new_user_session_path, notice: 'Data bundle was successfully created.'
  end
  helper_method :redirectToLogin

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_data_bundle
    @data_bundle = DataBundle.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def data_bundle_params
    params.require(:data_bundle).permit(:file, :name)
  end  
end

app/views/data_bundles/_form.html.slim
= form_for @data_bundle, multipart: true, html: {role: 'form'} do |f|
  = render partial: 'shared/errors', locals: {object: @data_bundle}
  .box-body
    .form-group
      label for="data_bundle_name" DataBundle name
      = f.text_field :name, class: 'form-control'
    .form-group
      label for="data_bundle_file"  File input
      = f.file_field :file
  /= f.remote_file_url
  .box-footer
    = f.submit 'Save', id: 'save_data_bundle', class: 'btn btn-primary'

app/views/data_bundles/edit.html.slim
section.content-header
  h1
    | Editing DataBundle
section.content
  .row
    .col-xs-12
      .box.box-primary
        # = render partial: 'form'
        | This option has been disabled by the administrator.
        
= link_to 'Show', @data_bundle
'|
= link_to 'Back', data_bundles_path

app/views/data_bundles/index.html.slim
section.content-header
  h1
    | Data Bundles
section.content
  .row
    - if user_signed_in?
      .col-xs-7
        .box
          .box-body.table-responsive.no-padding
            table.table.table-hover
              tbody
                tr
                  th Name
                  th Date
                  th Download
                  th Links
                - @data_bundles.each do |data_bundle|
                  tr
                    td
                      = data_bundle.name
                    td
                      = data_bundle.created_at.strftime('%d-%m-%Y %H:%M')
                    td
                      = link_to data_bundle.file_identifier, data_bundle.file.url
                    td
                      = link_to 'Visualize', data_bundle, id: "to_show_#{data_bundle.id}"
                    td
                      = link_to 'Delete bundle', data_bundle_path(data_bundle), method: :delete, data: {confirm: 'Are you sure?'}, id: "to_delete_#{data_bundle.id}"
            = paginate @data_bundles
      .col-xs-5
        .box.box-primary
          .box-header.with-border
            h3.box-title New Databundle
          = render partial: 'form'
    - else
      .col-xs-6
        .box
          .box-body
            | For use the databundle viewer you must be logged in
            = redirectToLogin

app/views/data_bundles/show.html.slim
section.content-header
  h1
    = "#{link_to 'DataBundle: ', data_bundles_path}#{@data_bundle.name}".html_safe

section.content
  .container-fluid
    .row-fluid
      .span8.well
        ul#subject.nav.nav-tabs
          li.active
            a data-target="#workflow" data-toggle="tab"  Workflow
          li
            a data-target="#provenance" data-toggle="tab"  Provenance
        .tab-content
          #workflow.tab-pane.active.fade.in 
            .box.box-default
              .box-body
                table.table.table-bordered
                  tbody
                    tr
                      td Workflow name
                      td
                        = @data_bundle.workflow.annotations.name
                    tr
                      td Authors
                      td
                        = @data_bundle.workflow.annotations.authors.join(' ')
                    tr
                      td Titles
                      td
                        = @data_bundle.workflow.annotations.titles.join(' ')
                    tr
                      td Description
                      td
                        = @data_bundle.workflow.annotations.descriptions.join(' ')
                    tr
                      td Semantic annotation
                      td
                        - if @data_bundle.workflow.annotations.semantic_annotation.nil?
                          | -
                        - else
                          = @data_bundle.workflow.annotations.semantic_annotation
                #wfContainer
                  svg#graphContainer
                button#saveWF.svgImage Save the workflow as image
                canvas#canvasWF height="500" style="display:none" width="960"


          #provenance.tab-pane
            - if @data_bundle.provenanceMain.present?
              .container-fluid
                .row-fluid
                  .span8.well
                    ul#diagramType.nav.nav-tabs
                      li.active
                        a#diagramSankey data-target="#provSankey" data-toggle="tab" Sankey
                      li
                        a#diagramMiserables data-target="#provCooccurrence" data-toggle="tab" Co-occurrence
                    .tab-content
                      #provSankey.tab-pane.active.fade.in 
                        .box.box-default
                          .box-body
                      #provCooccurrence.tab-pane
                        .box.box-default
                          .box-body
                            p#porder
                              | Order:
                              select#order
                                option value="name" by Name
                                option value="count" by Frequency
                                option value="type" by Type
                    .provCont
                      #mapContainer
                        svg#provContainer
                      button#enableZooming.svgImage alt=("Enabling zooming will mouse-mid button scrolling ability") type="submit" value="True" 
                        span Enable Zooming

                      button#savePROV.svgImage Save the provenance as image
                      canvas#canvasPROV height="500" style="display:none" width="960" 
            - else
              .row No data to display
              br
            


#data_bundle data-url=data_bundle_url(@data_bundle, format: :json)